### ISSUE TITLE
ID number and owned licenses

### ISSUE THREAD

**Issue by EGUltraTM** [jonassvensson4/jsfour-idcard#1]
Hi,
thanks a lot for this nice release but i cant see the ID number to search for on the mdc for example.

Also the driver license would be cool if you would see which licenses you owned there like, car, truck etc.
Or have i missed something?

**Comment by jonassvensson4** [comment]
This ID card won't show you the lastdigits which you need for the MDC. You have to tweak it so you can see them as well. Nothing I will add since some people don't use lastdigits in their DOB.

And yes I could add so it will display your licenses

**Comment by EGUltraTM** [comment]
Since i love your mdc and stuff sadly this is without the digits. LIked the idea of an personal number like its in many countrys. (Alternativly it would be nice to have the PSD of the stuff. So i could maybe change the image for legimitation script to use the design i really like it a lot)

The licenses would be more then awesome.

**Comment by jonassvensson4** [comment]
Added the licenses.
