### ISSUE TITLE
Nil upvalue

### ISSUE THREAD

**Issue by Mamafeinn** [jonassvensson4/jsfour-idcard#10]
Error running system event handling function for resource jsfour-idcard: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: @jsfour-idcard/server.lua:8: attempt to index a nil value
stack traceback:
	@jsfour-idcard/server.lua:8: in upvalue 'handler'
	citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
stack traceback:
	[C]: in function 'error'
	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
	citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>

**Comment by jonassvensson4** [comment]
Looks like it can't find the identifier `ESX.GetPlayerFromId(ID).identifier`. Are you sure you're using the events correctly?

**Comment by sh1noistaken** [comment]
Yes , 
![image](https://user-images.githubusercontent.com/49691112/61713847-30e19080-ad62-11e9-80e6-ca9c507139c2.png)
The error comes out when you want to show someone on Line 9, I use jsfour-register.

**Comment by jonassvensson4** [comment]
> Yes ,
> ![image](https://user-images.githubusercontent.com/49691112/61713847-30e19080-ad62-11e9-80e6-ca9c507139c2.png)
> The error comes out when you want to show someone on Line 9, I use jsfour-register.

You didn't answer my question. That's the event, how do you trigger it? Did you copy a trigger from the readme?

**Comment by sh1noistaken** [comment]
Yeah, I've already heard that when you trigger it, it's a mistake.
local player, distance = ESX.Game.GetClosestPlayer()

if distance ~= -1 and distance <= 3.0 then
  TriggerServerEvent('jsfour-idcard:open', GetPlayerServerId(PlayerId()), GetPlayerServerId(player))
else
  ESX.ShowNotification('No players nearby')
end

**Comment by jonassvensson4** [comment]
That looks fine. Try the following:
1. `local identifier = ESX.GetPlayerFromId(source).identifier`
2. If 1 doesn't work, try this: `local identifier = GetPlayerIdentifier(source)`

**Comment by ShinxD92** [comment]
I have the same error and probe with the codes and none works

**Comment by jonassvensson4** [comment]
> I also have that error, I already tried the codes and it doesn't come out to show the idcard
> 
> the error no longer appears in the console but it does not appear to show the "idcard"

You have that error but the error doesn't appear?

**Comment by ShinxD92** [comment]
> > I also have that error, I already tried the codes and it doesn't come out to show the idcard
> > the error no longer appears in the console but it does not appear to show the "idcard"
> 
> You have that error but the error doesn't appear?

 @jsfour-idcard/server.lua:8: attempt to index a nil value 
stack traceback: 
@jsfour-idcard/server.lua:8: in upvalue 'handler' 
citizen:/scripting/lua/scheduler.lua:169: in function <citizen:/scripting/lua/scheduler.lua:168> 
Error resuming coroutine: @jsfour-idcard/server.lua:8:

**Comment by gr4v86** [comment]
hi i was getting a similar issue and changed what you said but now i am getting

@jsfour-idcard/server.lua:9: attempt to index a nil value

**Comment by gr4v86** [comment]
-- Open ID card
RegisterServerEvent('jsfour-idcard:open')
AddEventHandler('jsfour-idcard:open', function(ID, targetID, type)
	local identifier = GetPlayerIdentifier(source)
	local _source 	 = ESX.GetPlayerFromId(targetID).source
	local show       = false

![image](https://user-images.githubusercontent.com/51834394/63459939-6ce53f80-c44d-11e9-928f-17be86c9f447.png)

**Comment by jonassvensson4** [comment]
That's because you haven't changed that line?.. It's still using ESX.GetPlayerFromId?

**Comment by gr4v86** [comment]
did you say to change that line? sorry if i misunderstood

local identifier = ESX.GetPlayerFromId(source).identifier
If 1 doesn't work, try this: local identifier = GetPlayerIdentifier(source)

I thought it was one or the other for the local identifier?

What would you suggest setting the local _source to?

**Comment by jonassvensson4** [comment]
It was that one that was causing the error. But as you can see there are 2 lines of code that uses that function. By fixing the first line you'll get another error on the second one. 

You can fix it the exact same way as you did earlier? But use target instead of source

**Comment by gr4v86** [comment]
Use target instead of source where? Sorry its been a long day lol

**Comment by jonassvensson4** [comment]
You should be able to just use the targetID.

Also, are you perhaps using kashacters?

**Comment by gr4v86** [comment]
No not using kashacters. We were thinking of using it though. Would this cause issues?

**Comment by jonassvensson4** [comment]
No I just know it messes with the player identifier. I guess it's just the ESX function that's broken for some servers then.

**Comment by ShinxD92** [comment]
![image](https://user-images.githubusercontent.com/52611202/63542356-d022b080-c4e5-11e9-90ca-d27c6a4a2063.png)
![image](https://user-images.githubusercontent.com/52611202/63542374-d9ac1880-c4e5-11e9-8e81-26d585add44e.png)

i need help  
This error has been released for a while in the server console

**Comment by jonassvensson4** [comment]
Since none seems to send any reply on this issue I'm closing it. Seems like the ESX.GetPlayerFromID is broken for some servers. If you get this error try to replace the server event with this one https://pastebin.com/XhyPP6Pg
