### ISSUE TITLE
Dynamic user images

### ISSUE THREAD

**Issue by BigGalch** [jonassvensson4/jsfour-idcard#12]
I've tried changing the init.js file to allow for dynic image files to replace the male and female.png. For example; If they are police it will display a police badge, Ambulance, their crest etc.

I assumed I could do it with this:

        if ( sex.toLowerCase() == 'm' ) {
          $('img').attr('src', 'assets/images/male.png');
          $('#sex').text('male');
		   } else if ( job == 'police' ) {
          $('img').attr('src', 'assets/images/police.png');
        } else
          $('img').attr('src', 'assets/images/female.png');
          $('#sex').text('female'); {
        }

But it clearly requires more. Can you offer some assistance?

**Comment by jonassvensson4** [comment]
Have you defined the variable `job`?

**Comment by BigGalch** [comment]
var job         = userData.job;

**Comment by BigGalch** [comment]
$(document).ready(function(){
  // LUA listener
  window.addEventListener('message', function( event ) {
    if (event.data.action == 'open') {
      var type        = event.data.type;
      var userData    = event.data.array['user'][0];
      var licenseData = event.data.array['licenses'];
      var sex         = userData.sex;
	  var job         = userData.job;

      if ( type == 'driver' || type == null) {
        $('img').show();
        $('#name').css('color', '#282828');

        if ( sex.toLowerCase() == 'm' ) {
          $('img').attr('src', 'assets/images/male.png');
          $('#sex').text('male');
		   } else if ( job == 'Met Police' ) {
          $('img').attr('src', 'assets/images/police.png');
        } else
          $('img').attr('src', 'assets/images/female.png');
          $('#sex').text('female'); {
        }

**Comment by jonassvensson4** [comment]
Did you just add that or did you also add the job column to the select query in the server.lua file?

**Comment by BigGalch** [comment]
It was already in there

**Comment by jonassvensson4** [comment]
It's not in the default server.lua but alright. Did you add the image to the __resource.lua?

**Comment by BigGalch** [comment]
Forgive me was added, but yes it's there

MySQL.Async.fetchAll('SELECT firstname, lastname, dateofbirth, sex, height, job FROM users WHERE identifier = @identifier', {['@identifier'] = identifier},

Yup resource.lua updated too. 

The result I'm getting is everyone is showing as female and no image change.

**Comment by jonassvensson4** [comment]
Oh okay. It's probably because you're checking the gender within the same if statement as the job.

**Comment by BigGalch** [comment]
I think I've managed to get it working by just splitting the two

         if ( job == 'police' ) {
          $('img').attr('src', 'assets/images/police.png');
		  } else {
          $('img').attr('src', 'assets/images/female.png');
		  }
		  
        if ( sex.toLowerCase() == 'm' ) {
          $('#sex').text('male');
        } else {
          $('#sex').text('female');
        }

**Comment by BigGalch** [comment]
Just running some tests

**Comment by BigGalch** [comment]
Sorted. Thank you :)
