### ISSUE TITLE
ID-Card isn't showing up on the latest FiveM version. (15.5.01)

### ISSUE THREAD

**Issue by xVelns** [jonassvensson4/jsfour-idcard#15]
Hello.

After going from zap to a dedicated server I noticed that there are 2 Scrollbar's.
On of the right side (vertical) and one on the bottom (horizontal).

After checking around it seems that this caused the issue:

https://i.imgur.com/01tDdgo.png

After stopping the resource, the Scrollbar's disappear.

Any help would be appreciated!

**Comment by jonassvensson4** [comment]
Looks like jQuery is broken. Try to re-download the resource.

**Comment by xVelns** [comment]
Thank you for getting back to me so fast.

Thanks it resolved it right away.
Looks like zap isn't copy-paste friendly. >:(

Much love. <3

**Comment by jonassvensson4** [comment]
No problems! :)

Changed title so it's easier for people to find it if they have the same issue.

If someone gets the same issue, try to re-download the resource or especially the jquery.js file before creating a new issue/commenting on this one.
