### ISSUE TITLE
Blanco id card

### ISSUE THREAD

**Issue by mBrabander** [jonassvensson4/jsfour-idcard#16]
I added your script to my server, did the key event thing...
Now it does show the id card but it doesnt seem to pull info from the database...

Do you know how to solve this?

https://prnt.sc/p08gfa

**Comment by jonassvensson4** [comment]
I'm sorry but how am I supposed to help you if that's all the info you're giving me?

Errors? 
Are you sure your character is saved correctly in your database?
Have you tried to log the userData array?

**Comment by mBrabander** [comment]
There are no errors popping up in the console....
My character is saved correctly into the database since im not getting any errors from that either....

have i tried to log the userData array?
No, i did not i guess... what do you mean by that?

**Comment by jonassvensson4** [comment]
There's a userData array in the javascript that contains all the information of the user. Log that to see what it contains. If it's empty you should print some tables on the server to see if it fetches anything

**Comment by mBrabander** [comment]
It's solved thanks for your help! 👍
