### ISSUE TITLE
Error server.lua

### ISSUE THREAD

**Issue by Patrickstek121** [jonassvensson4/jsfour-idcard#17]
Hello,

I get this error:  Failed to execute thread: server.lua:8: attempt to index a nil value

![image](https://user-images.githubusercontent.com/16652731/64081924-ca0fa980-cd07-11e9-85a4-a4038c2acf0c.png)

**Comment by jonassvensson4** [comment]
Issue already exists
https://github.com/jonassvensson4/jsfour-idcard/issues/10
