### ISSUE TITLE
Add a ID card

### ISSUE THREAD

**Issue by emiada** [jonassvensson4/jsfour-idcard#21]
Hey nice project could you help me i tryed to add a nother id (police-id) and it doesnt work

**Comment by jonassvensson4** [comment]
Help you how? How have you added it? Show some code? Are you getting any errors?

You can't just ask for help without providing some more information.

**Comment by emiada** [comment]
I added this to the server.lua
![image](https://user-images.githubusercontent.com/11033787/65773725-17cbd600-e13d-11e9-9cce-e0d6ea871089.png)

and tjis to the int.js (html\assets\js
![image](https://user-images.githubusercontent.com/11033787/65773901-6e391480-e13d-11e9-8413-17e08462f745.png)

This is the whol program
[jsfour-dna-master.zip](https://github.com/jonassvensson4/jsfour-idcard/files/3662981/jsfour-dna-master.zip)

The picture I added is for test reasons only

**Comment by emiada** [comment]
I'm sorry for forgeting the important stuff

**Comment by emiada** [comment]
do you have discord or something too? It's more easy to chat atleast for me. If you have and want my discord is: mada.lime#5815

**Comment by jonassvensson4** [comment]
That won't work since you're adding the police type inside the weapon type. You need to add the else statement to the other if statement.

**Comment by emiada** [comment]
Like this?
![image](https://user-images.githubusercontent.com/11033787/65783637-79e20680-e150-11e9-8f31-d14070321dce.png)

**Comment by jonassvensson4** [comment]
Spacing wont change anything. You have to move the end and close the weapon if statment above your type == police

**Comment by emiada** [comment]
like this:
![image](https://user-images.githubusercontent.com/11033787/65786137-45714900-e156-11e9-86bd-1aceff347f41.png)
or like this:
![image](https://user-images.githubusercontent.com/11033787/65786163-58841900-e156-11e9-98d8-1e8311f406b7.png)

**Comment by jonassvensson4** [comment]
None of them are correct. The 2nd one is the closest one but you have to remove the end. http://prntscr.com/pbuj1z

**Comment by emiada** [comment]
where shall I move it?

**Comment by jonassvensson4** [comment]
**remove**

**Comment by emiada** [comment]
ok and then it should work?

**Comment by jonassvensson4** [comment]
Try it out?

**Comment by emiada** [comment]
now it's showing the normal Id card

**Comment by emiada** [comment]
Do you have an idea why

**Comment by jonassvensson4** [comment]
No I don't. I haven't seen your client file. How do you trigger the server event?
