### ISSUE TITLE
Picture for ID card. Is it can set?

### ISSUE THREAD

**Issue by qq9906898** [jonassvensson4/jsfour-idcard#23]
Hello, great author, I am Chinese, and English is very bad.
Because this great work is lua+js. I really can't do anything about js. Can you help us with it?

**Comment by jonassvensson4** [comment]
I don't know what you're trying to do? Picture for ID card? Set? Set what? What picture are you talking about?

**Comment by qq9906898** [comment]
I managed to load a web image from SQL.
But this method is very inconvenient. Have you tried other more efficient methods?
https://cdn.discordapp.com/attachments/567712099640279061/630389414484246528/image_3.png

**Comment by jonassvensson4** [comment]
I'm assuming you want the ped mugshot on the ID card. Please see this issue https://github.com/jonassvensson4/jsfour-idcard/issues/22. I've listed 3 options which you could implement on your own.

**Comment by qq9906898** [comment]
thank you so much
