### ISSUE TITLE
the identity card appears to the spawn

### ISSUE THREAD

**Issue by hybridprod** [jonassvensson4/jsfour-idcard#25]
I have a problem hello jsfour! here I can talk to you freely .. I'm the same person who is writing to you [Release] jsfour-idcard [ESX] I solved with the server.lua now I have created this problem. when I get my ID card.

**Comment by hybridprod** [comment]
After this step it happened to me https://pastebin.com/XhyPP6Pg

**Comment by jonassvensson4** [comment]
I don't understand what your problem is? 

Show me some screenshot or the error if you get one.

**Comment by hybridprod** [comment]
https://ibb.co/VQC5Nnd

When I enter the game, my identity card appears

**Comment by jonassvensson4** [comment]
How do you trigger the server event? Looks like you're triggering it when the client has started?

**Comment by hybridprod** [comment]
When started it appears on the screen automatically

**Comment by jonassvensson4** [comment]
No. There's nothing that triggers that event by default. It's something you've added

**Comment by hybridprod** [comment]
So is it a third-party script that starts the process? I understand and maybe I also figured out which script .. I try to disable that script and let you know.. Thanks for your time and this super cool script!

**Comment by jonassvensson4** [comment]
I've just told you that there's nothing in the default script that shows you the idcard. It's something you've added yourself. Seems to me like you're triggering it once a client has loaded it. There's nothing I can do about it. You simply remove that trigger and it should work fine. I won't explain it once again. Good luck!
