### ISSUE TITLE
Firearm license shows even though I don't have a firearm license.

### ISSUE THREAD

**Issue by NicholasDilligaf** [jonassvensson4/jsfour-idcard#27]
Firearm license shows even though I don't have a firearm license.  Here's my server.lua.

https://pastebin.com/nF9GEsXM

And here what it looks like.
https://i.imgur.com/WBpr2jK.png

**Comment by jonassvensson4** [comment]
Update the resource?.. 

Instead of creating an issue please have a look at the latest files of the resource. You can clearly see that the latest update of the server.lua file implements the License check (7 months ago).
