### ISSUE TITLE
Add a check statement 

### ISSUE THREAD

**Issue by NicholasDilligaf** [jonassvensson4/jsfour-idcard#28]
Thanks for the help the other day! I finally got it working. How do I add a check statement if they have the item or not? If they don't have it, they won't be able to view their car license nor their weapon license. I already made the items for the licenses. So far I am at xPlayer.getInventoryitem('license') and here is the server.lua from jsfour-idcard.

https://pastebin.com/y5AE7NSk

**Comment by jonassvensson4** [comment]
I can't see where you've added xPlayer.getInventoryitem('license')?

**Comment by NicholasDilligaf** [comment]
I don't know where to put it.

**Comment by NicholasDilligaf** [comment]
And if I knew where, I don't know how to make a statement that will check if the player has the item in their inventory and if not, they won't be able to show or check their license.

**Comment by jonassvensson4** [comment]
You should try to add it by yourself without asking people for the correct solution. That's how you learn.

If you've tried it and still can't get it to work you could ask around on forums or Discord servers by providing them the code that you've just tried. Good luck!
