### ISSUE TITLE
Car licenses won't show up

### ISSUE THREAD

**Issue by NicholasDilligaf** [jonassvensson4/jsfour-idcard#29]
Even after editing the init.js, only the license card with no data shows up but the firearm and ID card are working great.

Here's the init.js:
https://imgur.com/a/TnRiZWR

Here's the server.lua:
https://imgur.com/a/TnRiZWR

Here's the screenshow of how it looks like:
https://imgur.com/a/BOaG9qE

**Comment by jonassvensson4** [comment]
Can't really help you since you've only provided a screenshot of your init.js file. 

Would also be better if you pasted your code on pastebin or something.

**Comment by NicholasDilligaf** [comment]
This is the paste bin for init.js:
https://pastebin.com/D73f3f4N

**Comment by NicholasDilligaf** [comment]
I finally got it working, just changed something in init.js. ;)

P.S I really love the way you help people in need, you guide them by teaching them not by giving solutions right off the bat. I look forward seeing you in the near future. ;)

**Comment by TheXtreamYT01** [comment]
@NicholasDilligaf  how do I fix this?
