### ISSUE TITLE
appending the text problem

### ISSUE THREAD

**Issue by TanguyOrtegat** [jonassvensson4/jsfour-idcard#32]
Triggering more then once the driver licence, does append the text and does not replace. Here is an example:

https://media.discordapp.net/attachments/630853992250867713/660944080666230785/7885.PNG?width=356&height=670

**Comment by TanguyOrtegat** [comment]
could be solved by:
$('#licenses').empty();

**Comment by jonassvensson4** [comment]
The html element gets removed once the ID card is closed. Does pretty much the same thing as .empty(). 

I'm not sure why you would open the ID card multiple times without closing it. If your server has that issue you could just reset everything when the card opens as well. I guess that's what you've figured out :)
