### ISSUE TITLE
Problem with Menu

### ISSUE THREAD

**Issue by TheMarecar12** [jonassvensson4/jsfour-idcard#33]
Hello mate. I use your jsfour-idcard for showing IDs to players. I added menu but it doesn't show up.
https://pastebin.com/fNWsAXHD

This is the code. When I press F5, menu doesn't show up and no errors are being dumped. Can you help me to fix this error?

**Comment by jnsvns** [comment]
You've added the function but you never call it, that's why it won't open

**Comment by SpiderAang** [comment]
How can i call it?
*Google Translate*
