### ISSUE TITLE
SHOWING ID CARD

### ISSUE THREAD

**Issue by uhamhz** [jonassvensson4/jsfour-idcard#35]
i have problem with showing id card,why the id card isn't coming out?

**Comment by jnsvns** [comment]
I'll have to see some code. How are you trying to show it?

**Comment by uhamhz** [comment]
@jonassvensson4 in client.lua?

**Comment by uhamhz** [comment]
![server 2 lua - Visual Studio Code 20_03_2020 13_31_34](https://user-images.githubusercontent.com/58426689/77141364-389f3380-6aaf-11ea-9711-085f45cb0cc5.png)

**Comment by jnsvns** [comment]
That's the server event yes. But how do you open the ID card?

**Comment by uhamhz** [comment]
![FiveM -  Precious RolePlay Indonesia  TEST SERVER  20_03_2020 15_06_00](https://user-images.githubusercontent.com/58426689/77146300-4d82c380-6abd-11ea-8130-d8c8559430e8.png)

**Comment by jnsvns** [comment]
Again.. I need to see some code, not just an ingame picture since I have no idea how you're opening the ID card. Show me the client sided code that you're trying to run.

**Comment by uhamhz** [comment]
https://imgur.com/undefined.png
https://imgur.com/jLyNBsD
new update error

**Comment by jnsvns** [comment]
Please use pastebin, hastebin or something else rather than taking a picture of the code.. I can't even see the whole code in that image?

**Comment by uhamhz** [comment]
https://pastebin.com/Qpjj88mS

**Comment by jnsvns** [comment]
I can't see where you've included ESX in the client file. And you can't just copy and paste everything you find in the readme file, it won't work. Please read the instructions once again, use the pastebin link under Usages if you can't find a solution on your own.

This is not a resource issue, you haven't implemented the events correctly.
