### ISSUE TITLE
jsfour-idcard doesn't work

### ISSUE THREAD

**Issue by reaLFOXY1337** [jonassvensson4/jsfour-idcard#38]
script is successfully loaded,without errors,but in game I can't show or see my id card or other cards..

**Comment by jnsvns** [comment]
You have to provide a bit more information than that. How are you trying to use it? Show me some code?

**Comment by reaLFOXY1337** [comment]
Can you please come to my server and see?There is no errors,nothing in console,just id card and other won't show when I click F5 > My documents > ID Card show and see

**Comment by reaLFOXY1337** [comment]
Server is Balkan Vision RP [NEMA WL] [DISCORD:discord.gg/invite]

I can't show you here more proofs,because there is no errors

**Comment by reaLFOXY1337** [comment]
> You have to provide a bit more information than that. How are you trying to use it? Show me some code?

Code isn't changed,nothing changed,just added and started like this
start jsfour-idcard

**Comment by jnsvns** [comment]
No I won't join your server. If you've just dropped it into your resources folder and started it I'm not surprised you can't get it to work. 

Please read the repos readme.... It clearly says that you need to add a couple of rows of code which you can find under [usage](https://github.com/jonassvensson4/jsfour-idcard#usage).
