### ISSUE TITLE
Resource is taking over than 2ms 

### ISSUE THREAD

**Issue by xYouLL** [jonassvensson4/jsfour-idcard#39]
Hello I want to know why the resource take more than 2 CPU ms, is it a fixable thing?
Thanks

**Comment by jnsvns** [comment]
Are you sure it takes 2ms? Sounds a bit absurd. Could you screenshot it?

I'm guessing it depends on how you use it, if you spam the events I guess any resource could go up that high.

**Comment by xYouLL** [comment]
https://i.gyazo.com/f22ee05d36c5941fce5d57dcebf424e6.png

I didn't modify nothing, hmm I'll check if I forgot to don't spam events

**Comment by xYouLL** [comment]
```
if val == 'checkID' then 
TriggerEvent('3dme:shareDisplay', "controlla i documenti")
TriggerServerEvent('jsfour-idcard:open', GetPlayerServerId(closestPlayer),
GetPlayerServerId(PlayerId()))
elseif val == 'checkDriver' then 
TriggerEvent('3dme:shareDisplay', "controlla i documenti")
TriggerServerEvent('jsfour-idcard:open', GetPlayerServerId(closestPlayer), GetPlayerServerId(PlayerId()), 'driver')
elseif val == 'checkFirearms' then 
TriggerEvent('3dme:shareDisplay', "controlla i documenti")
TriggerServerEvent('jsfour-idcard:open', GetPlayerServerId(closestPlayer), GetPlayerServerId(PlayerId()), 'weapon')
end
```

This is the only part where I've used it, my policejob where policeman's can see documents of closestPlayer. But this is inside a menu so it's impossible that is taking ms even if it's close

**Comment by jnsvns** [comment]
If you just run the resource itself without modifying it, it should be around 0.02ms. This resource is very minimal and barely has anything in it.  

I'm not sure how I'm supposed to help you. If the resource was written in javascript I could remove the thread if it's not in use. But having one single thread running shouldn't make the resource take 2ms.

Check your console to make sure it's not spamming any errors. You could check if it starts at 2 ms or if it gets higher if you're doing something specific.

**Comment by xYouLL** [comment]
Solved, I had instantiated esx object doing `while true do`, instead of doing `while ESX == nil do`.
Sorry for the disorder, thanks the same :)
