### ISSUE TITLE
Mugshot + person number

### ISSUE THREAD

**Issue by johnnypernik** [jonassvensson4/jsfour-idcard#4]
Hey, what about adding person number from jsfour-register? Its missing part in workflow with MDC.
Ofc it will always show actual photo (i dont know if we can export or save mugshots), but still awesome!
https://esx-org.github.io/es_extended/client/functions/game/getpedmugshot/

**Comment by jonassvensson4** [comment]
Won't add it since I already have a script for that. A guy already made some changes to my script to include that so he might fork it and post the link.

And no mugshots are not something we can export out of  the game., it's saved in GTAs memory.

**Comment by jonassvensson4** [comment]
https://github.com/EGUltraTM/jsfour-idcard
