### ISSUE TITLE
jsfour-idcard/server.lua:8: attempt to index a nil value

### ISSUE THREAD

**Issue by KingMacking** [jonassvensson4/jsfour-idcard#43]
Theres no solution for this already, so what can i do ? hope you know what to do with this jsfour :/

**Comment by jnsvns** [comment]
https://github.com/jonassvensson4/jsfour-idcard/issues/10 Have you had a look at this?

**Comment by KingMacking** [comment]
Yup, still with the error, i think is because the way you try to pull the identifier, but idk which is the correct wayt to do it

**Comment by jnsvns** [comment]
That's really weird that you're getting the same error even with that code that I posted in that issue since it's not trying to index a value at line 8.

Are you sure that you've tried the correct code? The `GetPlayerIdentifier `native should grab the first available ID. And the first ID in that "list" should be the Steam ID. If that isn't available it will grab the license ID.

**Comment by KingMacking** [comment]
I tryied with the 2 ones you poste, the first stills giving me the 8 line error, and the second one gives me a 9 line error :/, i mean, the menu works (i think, we didnt open yet) but its anoying to see that error in the console

**Comment by jnsvns** [comment]
The second one? I mean I'm not sure how I'm supposed to help you. If you're using the code that's at the bottom of that issue I linked you shouln't be able to get this error since it's not trying to index a value at line 8. Could you upload the code that you're trying to run to pastebin?

**Comment by alexxrsd** [comment]
I have the same issue here aswell.

**Comment by jnsvns** [comment]
Upload your server.lua to pastebin or something.

**Comment by alexxrsd** [comment]
https://pastebin.com/7HdGqtEe

**Comment by jnsvns** [comment]
If you scroll up there's a link to another issue which has this link at the bottom: https://pastebin.com/XhyPP6Pg

Try that

**Comment by alexxrsd** [comment]
When edited, i get this clientsided, no errors in console https://imgur.com/a/xJAJzF2

**Comment by jnsvns** [comment]
You have a broken jquery file, redownload it.

**Comment by alexxrsd** [comment]
Thanks man! it works like a charm!
