### ISSUE TITLE
Add a New Driver category in license card

### ISSUE THREAD

**Issue by ghost** [jonassvensson4/jsfour-idcard#44]
Hello, 
im trying to add a new category for my license card but when i add it the other not showing.

Thats` what ive changed inb server.lua: 

	function (user)
		if (user[1] ~= nil) then
			MySQL.Async.fetchAll('SELECT type FROM user_licenses WHERE owner = @identifier', {['@identifier'] = identifier},
			function (licenses)
				if type ~= nil then
					for i=1, #licenses, 1 do
						if type == 'driver' then
							if licenses[i].type == 'drive' or licenses[i].type == 'drive_bike' or licenses[i].type == 'drive_truck' or licenses[i].type == 'drive_bus' then
								show = true
							end
						elseif type =='weapon' then
							if licenses[i].type == 'weapon' then
								show = true
							end
						end
					end
				else
					show = true
				end>

And this is in init.js:

if ( type == 'driver' ) {
          if ( licenseData != null ) {
          Object.keys(licenseData).forEach(function(key) {
            var type = licenseData[key].type;

            if ( type == 'drive_bike') {
              type = 'A';
            } else if ( type == 'drive_truck' ) {
              type = 'Ц';
            } else if ( type == 'drive' ) {
              type = 'Б';
            } else if ( type == "drive_bus")

            if ( type == 'A' || type == 'Ц' || type == 'Б' || type == 'Д' ) {
              $('#licenses').append('<p>'+ type +'</p>');
            }
          });
        }

The problem is that when ive add the 4 category its not showing the other and when i remove it then i can see them.

**Comment by jnsvns** [comment]
I mean you're missing a couple of brackets in the init.js, You should get a couple of errors in the console. 

If you fix those it should be able to get into the new else statement that you've added: 
`} else if ( type == "drive_bus")` 
That's how far it will go, it won't make it into the other if statement since type is equal to drive_bus and not A, Ц...
