### ISSUE TITLE
ID card 

### ISSUE THREAD

**Issue by MGXNOBODY** [jonassvensson4/jsfour-idcard#48]
So your id card script does not let me get to a menu to look at my id card or open the menu pls get back to me

**Comment by jnsvns** [comment]
I'm not entirely sure on how I'm supposed to help you. Could you upload your client file to pastebin or something?

**Comment by MGXNOBODY** [comment]
So I have to edit the client but what I’m trying to say is what do I copy
and paste into that and I’ll upload the client when I get a moment
