### ISSUE TITLE
SCRIPT ERROR: @jsfour-idcard/server.lua:9: attempt to index a nil value

### ISSUE THREAD

**Issue by Mono-94** [jonassvensson4/jsfour-idcard#49]
consola
SCRIPT ERROR: @jsfour-idcard/server.lua:9: attempt to index a nil value
server.lua
https://pastebin.com/9eAkqaJn

**Comment by jnsvns** [comment]
https://github.com/jonassvensson4/jsfour-idcard/issues/10
