### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by btwentyone** [jonassvensson4/jsfour-idcard#5]
Hello,
It would be nice to replace the photo.png file with a more realistic headshot of the character.

**Comment by jonassvensson4** [comment]
Sure I'm open for suggestions on how to accomplish that. 

There's a function in the game that returns the headshot of the character but you can't send that file to the javascript. The file is within the game and can't be reached.

So the easiest way would be if players took a screenshot and uploaded it to gyazo or something.. But that's kinda ugly if you ask me.

**Comment by btwentyone** [comment]
It is a shame that this is not compatible because it will give a more RP side
