### ISSUE TITLE
esx_policejob adapt

### ISSUE THREAD

**Issue by xBrunex** [jonassvensson4/jsfour-idcard#50]
Hello

I tried alot but i can't find the way...

I want adapt your script to the esx_policejob, when police want to see the ID or the driver licence.

Can you help me pls ?

Thanks

**Comment by jnsvns** [comment]
What have you tried so far?

**Comment by xBrunex** [comment]
Basicaly when Im with the cop job when i ask the target to show its ID it shows mine instead

I need a trigger in which I can see the ID from someone without needing his/her permission

**Comment by jnsvns** [comment]
Yeah I get that but you said that you've tried a lot. Let me see some code examples and I'll try to help you fix it

**Comment by xBrunex** [comment]
well forget i got police working 100% now

but thanks
