### ISSUE TITLE
MySQL Error

### ISSUE THREAD

**Issue by DzonnyX** [jonassvensson4/jsfour-idcard#51]
Hey, when i click f5 and show your id nothing happends, and i get this message i cmd
[ERROR] [MySQL] [jsfour-idcard] An error happens on MySQL for query "SELECT firstname, lastname, dateofbirth, sex, height, lastdigits FROM users WHERE identifier = 'steam:11000013d88fc51'": ER_BAD_FIELD_ERROR: Unknown column 'lastdigits' in 'field list'
SCRIPT ERROR: @jsfour-idcard/server.lua:14: attempt to index a nil value (local 'user')
> ref (@jsfour-idcard/server.lua:14)
>  (@mysql-async/mysql-async.js:14898)

https://prnt.sc/tuqs1s

**Comment by jnsvns** [comment]
It clearly says what the problem is. You're not using the original version of my resource, you're using a modified version that's using a column in the users table that's called "lastdigits". You don't have that column and that's why you're getting the error.
