### ISSUE TITLE
Id card usable by item.

### ISSUE THREAD

**Issue by Hambbu** [jonassvensson4/jsfour-idcard#52]
How am i able to create idcard item that once used will trigger event to show the idcard to the person next to you?
esx.registerusableitem lets you create an item, but how am i able to trigger the events to get it work?

**Comment by jnsvns** [comment]
Since you need to get the closest player you'll probably need to create a client sided event which you can run from the server. You pretty much have everything you need in the examples found at the bottom of the repo.
