### ISSUE TITLE
Function opens

### ISSUE THREAD

**Issue by MainaGioia82** [jonassvensson4/jsfour-idcard#7]
how do I remove the function that opens the license with “E” and leave it that opens only with the menu?

**Comment by jonassvensson4** [comment]
There's no "function that opens the license with E" in the default script. 

That's something you've added to the script which doesn't make any sense since you don't want it? There's a example menu if you scroll down. Look at that one.

**Comment by MainaGioia82** [comment]
No I just wanted to see it since the menu opens and not even if you press E

**Comment by jonassvensson4** [comment]
What?

**Comment by MainaGioia82** [comment]
solved bro, obviously I changed something! sorry for disturbing
