### ISSUE TITLE
Drive-Lizens

### ISSUE THREAD

**Issue by Matetv** [jonassvensson4/jsfour-idcard#8]
Hello! How can I show someone my driving license? I have tried several times before. It does not work! Is not there help somewhere?

**Comment by jonassvensson4** [comment]
What have you tried?

**Comment by Duqino** [comment]
Think the last fivem update broke it. It worked before.

[![Screenshot from Gyazo](https://gyazo.com/dfb77e52839f63c2b846ccae62a82646/raw)](https://gyazo.com/dfb77e52839f63c2b846ccae62a82646)
