### ISSUE TITLE
Think the last fivem update broke it. It worked before.

### ISSUE THREAD

**Issue by jonassvensson4** [jonassvensson4/jsfour-idcard#9]
Think the last fivem update broke it. It worked before.

[![Screenshot from Gyazo](https://gyazo.com/dfb77e52839f63c2b846ccae62a82646/raw)](https://gyazo.com/dfb77e52839f63c2b846ccae62a82646)

if ( sex.toLowerCase() == 'm' ) {

[![Screenshot from Gyazo](https://gyazo.com/42a97369d71b21024401e00c2dc78546/raw)](https://gyazo.com/42a97369d71b21024401e00c2dc78546)

or its something else :)

I figured out my problem. Hope you know how to fix it. It wont add the sex in to the database....

_Originally posted by @Duqino in https://github.com/jonassvensson4/jsfour-idcard/issues/8#issuecomment-510634848_

**Comment by jonassvensson4** [comment]
Dude. Please don't post that issues in another issue that doesn't have anything to do with each other.. 

My script doesn't add the sex to the database. If you open the server.lua you'll only see one select query. That's all it does, it SELECTS the data from the database. Which means there's something else that's causing your issue and not my script.

**Comment by Duqino** [comment]
Sorry about that. I thought i had the same problem.
